### ISSUE TITLE
Exception name 'status' is not defined - not json

### ISSUE THREAD

**Issue by brunosso** [binh-bk/energy-meter#1]
I think in the mqtt_logger.py at the 49 line the code

`file_log.to_log(data, json_=status)`

must be

`file_log.to_log(data, json_=sensor)`

**Comment by bi2air** [comment]
Thank @brunosso  for noting this. I updated the script in both files. Basically, the `json_`  flag lets the function in `file_log` triggered the JSON or CSV format.
The updated script in line 47 looks like this:
`file_log.to_log(data, json_=True)`
